### PR TITLE
Sfs branding

### PR DESCRIPTION
**Pull request by kairstenfay**
Update the SCAN IRB results templates to use the new SFS logo.

### CODE REVIEW

**Comment by kairstenfay** [comment]
[Rebrand existing SCAN PDFs as "Seattle Flu Study, powering SCAN & Husky Coronavirus Testing"](https://trello.com/c/qCkbDKT6/763-rebrand-existing-scan-pdfs-as-seattle-flu-study-powering-scan-husky-coronavirus-testing)

**Comment by kairstenfay** [comment]
Here's a preview. 
image

**Review by kschwabefry — APPROVED** [review]
🥇 for the new logo

**Comment by joverlee521** [comment]
I assume we need to change the logo here just like we did for the website?

**Comment by kairstenfay** [comment]
> I assume we need to change the logo here just like we did for the website?

Good question. I was under the assumption that the need for plain SFS + BBI logos was specific to the UW Reopening -- since we're returning results still for SCAN + will be for other, non-UW SFS studies, I assume the SFS + partners logo is ok here and on the results portal?

**Comment by kairstenfay** [comment]
> > I assume we need to change the logo here just like we did for the website?
> 
> Good question. I was under the assumption that the need for plain SFS + BBI logos was specific to the UW Reopening -- since we're returning results still for SCAN + will be for other, non-UW SFS studies, I assume the SFS + partners logo is ok here and on the results portal?

I believe that the logo with all study partners can remain for the purpose of RoR, according to Misja.

**Review by tsibley — APPROVED** [review]
Looks great, thanks! When this is deployed, we'll want to avoid triggering re-generation of all existing reports.

I'll also note that this cuts the file size of each PDF from 60KiB → 10KiB. :tada: (Because the logo is now a vector graphic, not a raster image.)

**Comment by kairstenfay** [comment]
> Looks great, thanks! When this is deployed, we'll want to avoid triggering re-generation of all existing reports.
> 
> I'll also note that this cuts the file size of each PDF from 60KiB → 10KiB. tada (Because the logo is now a vector graphic, not a raster image.)

Neat, I missed the size reduction!

I think by default we only generate PDFs for new results via the `backoffice` repo.

**Comment by tsibley** [comment]
> I think by default we only generate PDFs for new results via the `backoffice` repo.

Ah, that's right. I was thinking the updated Docker image version for the PDF updates would trigger new generation too, but it's just results data changes.

**Comment by kairstenfay** [comment]
> > > I assume we need to change the logo here just like we did for the website?
> > 
> > 
> > Good question. I was under the assumption that the need for plain SFS + BBI logos was specific to the UW Reopening -- since we're returning results still for SCAN + will be for other, non-UW SFS studies, I assume the SFS + partners logo is ok here and on the results portal?
> 
> I believe that the logo with all study partners can remain for the purpose of RoR, according to Misja.

Silly me, I forgot Rule 2 of the SFS dev team club -- Jover is always right! I pushed a new commit with the latest approved logo. Preview:
image

**Pull request merged**
