### PR TITLE
Irb/ko

### PR DESCRIPTION
**Pull request by kairstenfay**
Translate SCAN IRB lab result template into Korean. Awaiting validation from a native speaker.

### CODE REVIEW

**Comment by kairstenfay** [comment]
[SCAN IRB: Korean](https://trello.com/c/SLMQ7w91/656-scan-irb-korean)

**Review by ghost — APPROVED** [review]

**Review by kschwabefry — APPROVED** [review]

**Comment by kairstenfay** [comment]
Just got the update that this PR is no good because the rendered template is missing spaces. 
This problem also exists in the `scan/` template FWIW.

**Comment by kairstenfay** [comment]
[Fix borked Korean template](https://trello.com/c/JIX7PVs9/686-fix-borked-korean-template)

**Comment by tsibley** [comment]
> the rendered template is missing spaces.

Whups. Is this because spaces are missing in the source LaTeX or because the spaces are going missing?

**Comment by kairstenfay** [comment]
> > the rendered template is missing spaces.
> 
> Whups. Is this because spaces are missing in the source LaTeX or because the spaces are going missing?

The source LaTeX code has spaces. The rendered PDF only has spaces after punctuation and between-word spaces are missing.

**Comment by tsibley** [comment]
The xeCJK package seems to have a `space` option for this.

```patch
diff --git a/scan-irb/report-ko.tex b/scan-irb/report-ko.tex
index 7455dd6..11d3c93 100644
--- a/scan-irb/report-ko.tex
+++ b/scan-irb/report-ko.tex
@@ -17,7 +17,7 @@
 \usepackage{multirow}
 \usepackage{pbox}
 \usepackage{enumitem}
-\usepackage{xeCJK}
+\usepackage[space]{xeCJK}

 % fonts
 \usepackage{fontspec}
```

Before:

Screenshot from 2020-07-27 16-31-38

After:

Screenshot from 2020-07-27 16-32-05

**Comment by kairstenfay** [comment]
> The xeCJK package seems to have a `space` option for this.
> 
> ```diff
> diff --git a/scan-irb/report-ko.tex b/scan-irb/report-ko.tex
> index 7455dd6..11d3c93 100644
> --- a/scan-irb/report-ko.tex
> +++ b/scan-irb/report-ko.tex
> @@ -17,7 +17,7 @@
>  \usepackage{multirow}
>  \usepackage{pbox}
>  \usepackage{enumitem}
> -\usepackage{xeCJK}
> +\usepackage[space]{xeCJK}
> 
>  % fonts
>  \usepackage{fontspec}
> ```
> 
> Before:
> 
> Screenshot from 2020-07-27 16-31-38
> 
> After:
> 
> Screenshot from 2020-07-27 16-32-05

Awesome find! I just tried to reverse engineer your troubleshooting process and found [this LaTeX exchange post](https://tex.stackexchange.com/questions/17292/how-to-write-spaces-between-korean-words-with-xecjk) whose accepted answer describes a similar approach. Thanks!

**Comment by kairstenfay** [comment]
Spaces are now typeset for Korean in the scan/ and scan-irb/ templates.

**Comment by kairstenfay** [comment]
Ah, I need to update the scan-irb template with the new language around swab type and staff observed variables.

**Pull request closed without merging**
