### PR TITLE
Irb spanish

### PR DESCRIPTION
**Pull request by kairstenfay**
Translate the English SCAN IRB template into Spanish. 

~Pending validation by native speakers.~

### CODE REVIEW

**Comment by kairstenfay** [comment]
[SCAN IRB translations](https://trello.com/c/yQR01au0/629-scan-irb-translations)

**Comment by kairstenfay** [comment]
~I just added zh-Hant to this PR because I recently learned we are trying to go live with Traditional Chinese by the end of the week.~
Ugh, wrong repo. Meant to post this in https://github.com/seattleflu/id3c-customizations/pull/111

**Review by joverlee521 — APPROVED** [review]

**Comment by kairstenfay** [comment]
This template has been validated by a native Spanish speaker.

**Comment by kairstenfay** [comment]
These commits now live at https://github.com/seattleflu/lab-result-reports/pull/18

**Pull request closed without merging**
